### ISSUE TITLE
Toolkit Basemap Gallery doesn't display the Thumbnails properly

### ISSUE THREAD

**Issue by LuisRguezEsriSpain** [Esri/arcgis-maps-sdk-dotnet-toolkit#530]
I am developing an application with MAUI.

- Product: ArcGIS Maps SDK for .NET
- Version: 200.2
- Project template: ArcGIS Maps SDK .NET MAUI App (Esri)
- Framework: .NET 7.0
- Toolkit Basemap Gallery widget
 
When I run de app by using "Samsung Galaxy Tab A SM-T510" and "Samsung Galaxy Tab A SM-T580", Toolkit Basemap Gallery widget doesn't display the Thumbnails properly.

![BasemapGalleryThumbnails](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/13570124/7731ddfe-5eb5-4aaa-a3b1-563f4a4cb3a6)

After creating a Esri Case, Esri recommend me submit a new Issue.

**Comment by dotMorten** [comment]
@LuisRguezEsriSpain Would you be able to share a small sample that reproduces the issue>

**Comment by LuisRguezEsriSpain** [comment]
I share a small sample.

[PoCDrones.zip](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/files/13182592/PoCDrones.zip)

**Comment by dotMorten** [comment]
Thank you. Were you only seeing this on Android, or only on certain Android devices? I see the basemaps both on Windows and on my Android:
![image](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/1378165/c7ffc803-be69-4263-ba7f-db1305782075)

**Comment by LuisRguezEsriSpain** [comment]
Hi Morten,

I only see Thumbnails on certain Android devices.

Por example:

- I see Thumbnails on mobiles Miui 10 and Samsung Galaxy A52s
- I don't see Thumbnails on tablets "Samsung Galaxy Tab A SM-T510" and "Samsung Galaxy Tab A SM-T580"

**Comment by dotMorten** [comment]
It looks like it is hitting this fallback:

https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/8e5bc024f51beea413b3f11541ed662854e38323/src/Toolkit/Toolkit.Maui/BasemapGallery/ByteArrayToImageSourceConverter.cs#L34

That data should be coming from here:
https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/8e5bc024f51beea413b3f11541ed662854e38323/src/Toolkit/Toolkit/UI/Controls/BasemapGallery/BasemapGalleryItem.cs#L100

Since I can't reproduce, would you be able to debug what is happening on your specific Android devices and see why the thumbnails fail to load?

**Comment by LuisRguezEsriSpain** [comment]
Hi Morten,

This is the debug's result.

`at RuntimeCoreNet.GeneratedWrappers.CoreImage.GetEncodedBuffer()
at Esri.ArcGISRuntime.UI.RuntimeImage.GetEncodedBufferAsync(CancellationToken cancellationToken)
at PoCDrones.BasemapGallery.BasemapGalleryItem.LoadImage() in C:\LuisRodriguez\Proyectos\ENAIRE\200_2\Incidencia\PoCDrones\PoCDrones\BasemapGallery\BasemapGalleryItem.cs:line 107
`

![BasemapGalleryThumbnailsDebug1](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/13570124/a7c45050-1a8d-4246-a5df-c7d1c2399737)

![BasemapGalleryThumbnailsDebug2](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/13570124/1c4b9fca-9f55-4d78-a2b4-fb2731386b07)

**Comment by dotMorten** [comment]
Thank you for the detailed screenshots. `[InvalidProgramException]` sounds like something went wrong in .NET or the compilation: https://learn.microsoft.com/en-us/dotnet/api/system.invalidprogramexception?view=net-7.0
Is your .NET up to date? Any chance you could also try with the latest .NET 8?

**Comment by LuisRguezEsriSpain** [comment]
Hi Morten,

I don't see how to create a ArcGIS Maps SDK .NET MAUI project using .NET.

![DotNet8_1](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/13570124/f13e54e7-dd75-4171-9b6b-ba643e1aca78)

I also don't see a way to change an existing project's .NET Framework.

![DotNet8_2](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/13570124/14d3a114-d09a-4118-a4ba-1d1fdde0fa0b)

**Comment by dotMorten** [comment]
.NET 8 shipped as final yesterday. If you update your visual studio to latest, you should now see it in your dropdown (before this you needed the preview release)

**Comment by LuisRguezEsriSpain** [comment]
Hi Morten,

I've installed the latest versión of visual studio.

![LatestVSVersion](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/13570124/a25dceca-4554-4c2d-9ba9-102ebc6e1195)

 I've also installed ArcGIS_Maps_SDK_DotNet_Templates_200_3_0.vsix.

In project propertiens I cannot choose either "Target Android Framework" or "Minimum Target Android Framework".

![TargetAndoird FW](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/13570124/f21db591-d1ff-4214-9b34-3cce095e80bc)

In addition to this issue I have others issues:
* When I change content of appicon.svg and appiconfg.svg I get this error when the project is built.
  
![ManifestError](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/13570124/2b250cef-babd-4e54-9335-b2ef8d916852)

* In Android app I cannot see svg icons as souce if ImageButton
* In Android app I cannot change IsEnabled property of "Frame" Maui controls by code

**Comment by dotMorten** [comment]
@LuisRguezEsriSpain are you able to build a normal .NET MAUI app targeting .NET 8? Most of the settings you refer too are easiest set in the .csproj file directly.

**Comment by LuisRguezEsriSpain** [comment]
@dotMorten I've done this workaround in BasemapGalleryItem class and work properly:

        private async Task LoadImage()
        {
            IsLoadingThumbnail = true;
            try
            {
                await (Thumbnail?.LoadAsync() ?? Task.CompletedTask);

                if (Thumbnail?.LoadStatus == LoadStatus.Loaded)
                {
                    var stream = await Thumbnail.GetEncodedBufferAsync();
                    var buffer = new byte[stream.Length];
                    await stream.ReadAsync(buffer, 0, (int)stream.Length);
                    ThumbnailData = buffer;
#if WINDOWS_XAML
                    ThumbnailBitmap = await Thumbnail.ToImageSourceAsync();
#endif
                }
                _hasLoaded = true;
            }
            catch (Exception ex)
            {
                await LoadImageAux();
            }
            finally
            {
                IsLoadingThumbnail = false;
            }
        }

        private async Task LoadImageAux()
        {
            try
            {
                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, Thumbnail.Source);
                HttpClient client = new HttpClient(new HttpClientHandler());
                var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
                var content = response.EnsureSuccessStatusCode();
                var streamRes = await content.Content.ReadAsStreamAsync();
                byte[] buffer = new byte[16 * 1024];
                using (MemoryStream ms = new MemoryStream())
                {
                    int read;
                    while ((read = await streamRes.ReadAsync(buffer, 0, buffer.Length)) > 0)
                    {
                        ms.Write(buffer, 0, read);
                    }
                    ThumbnailData = ms.ToArray();
                }
            }
            catch (Exception ex2)
            {
            }
        }
